/* eslint  import/prefer-default-export: "off" */
export const FETCH_PUBLICATIONS_REQUEST = 'FETCH_PUBLICATIONS_REQUEST';
export const FETCH_PUBLICATIONS_SUCCESS = 'FETCH_PUBLICATIONS_SUCCESS';
export const FETCH_PUBLICATIONS_FAILURE = 'FETCH_PUBLICATIONS_FAILURE';

export const SUBSCRIPTION_CLEAR = 'SUBSCRIPTION_CLEAR';
export const SUBSCRIPTION_REQUEST = 'SUBSCRIPTION_REQUEST';
export const SUBSCRIPTION_SUCCESS = 'SUBSCRIPTION_SUCCESS';
export const SUBSCRIPTION_FAILURE = 'SUBSCRIPTION_FAILURE';

export const FETCH_GENES_AUTOCOMPLETE_LIST_REQUEST =
  'FETCH_GENES_AUTOCOMPLETE_LIST_REQUEST';
export const FETCH_GENES_AUTOCOMPLETE_LIST_SUCCESS =
  'FETCH_GENES_AUTOCOMPLETE_LIST_SUCCESS';
export const FETCH_GENES_AUTOCOMPLETE_LIST_FAILURE =
  'FETCH_GENES_AUTOCOMPLETE_LIST_FAILURE';
export const CLEAR_GENES_AUTOCOMPLETE_LIST = 'CLEAR_GENES_AUTOCOMPLETE_LIST';
export const SET_SEARCH_SELECTED_GENES = 'SET_SEARCH_SELECTED_GENES';
export const SET_SEARCH_CONDITION = 'SET_SEARCH_CONDITION';

export const SET_GENE_SELECTION_IN_FILTERS = 'SET_GENE_SELECTION_IN_FILTERS';
export const PUBMED_URL = 'https://www.ncbi.nlm.nih.gov/pubmed';
